contact_links:
  - name: I have a question about Eleventy
    url: https://github.com/11ty/eleventy/discussions/
    about: General education topics should be filed on our Discussions board e.g. “How do I do this in Eleventy?” or “Can Eleventy do this?” (Please search existing discussions first!)
  - name: I have an idea or feature request for Eleventy
    url: https://github.com/11ty/eleventy/discussions/new?category=enhancement-queue
    about: Enhancement or new Features. e.g. “I wish Eleventy did this.” Suggest an idea! (Please search existing discussion first!)
  - name: Some docs are missing or inaccurate!
    url: https://github.com/11ty/11ty-website/issues
    about: Something missing from the documentation? Something wrong? Something just downright confusing? Tell us!
  - name: I have a feature request for the docs
    url: https://github.com/11ty/11ty-website/discussions/categories/enhancement-queue
    about: Enhancement or new Features for the documentation. e.g. “I wish the Eleventy docs did this.” Suggest an idea! (Please search existing discussions first!)
  - name: Discord Community
    url: https://discord.gg/GBkBy9u
    about: Ask the community on Discord
